### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by Mr-SD** [bizreach/aws-dynamodb-scala#11]
// Query with case class mapping
    val list: Seq[Member] = Members.query.keyConditions { t =>
      t.country -> DynamoDBCondition.eq("Japan") :: t.id -> DynamoDBCondition.eq(1) :: Nil
    }.list[Member]

Members.query.keyConditions doesn't seem to be part of the API any longer, the example on readme doesn't work.

**Comment by takezoe** [comment]
@Mr-SD Fixed example in README. Thanks!
