### ISSUE TITLE
version 0.0.5?

### ISSUE THREAD

**Issue by dtboctor** [bizreach/aws-dynamodb-scala#12]
It doesn't appear to be in maven? 
https://mvnrepository.com/artifact/jp.co.bizreach/aws-dynamodb-scala_2.11

**Comment by dtboctor** [comment]
I guess it's only compiled for 2.12, is it possible to get it compiled and available for 2.11?

**Comment by takezoe** [comment]
0.0.5 has been built for Scala 2.12:
https://mvnrepository.com/artifact/jp.co.bizreach/aws-dynamodb-scala_2.12

**Comment by takezoe** [comment]
@dtboctor Sorry, I missed previous your comment. OK, I will try to cross compile. But I would like to release it as 0.0.6, not 0.0.5. Does it sufficient you?

**Comment by takezoe** [comment]
0.0.6 for Scala 2.11 and 2.12 has been released.

- https://search.maven.org/#artifactdetails%7Cjp.co.bizreach%7Caws-dynamodb-scala_2.12%7C0.0.6%7Cjar
- https://search.maven.org/#artifactdetails%7Cjp.co.bizreach%7Caws-dynamodb-scala_2.11%7C0.0.6%7Cjar

**Comment by dtboctor** [comment]
Awesome, thanks so much.
